export const types = [
  'arrow-down',
  'passenger-flow-analysis',
  'area',
  'loading',
  'distribution',
  'portrait-match',
  'blacklist',
  'data',
  'statistic',
  'leader',
  'face-recognition',
  'monitor',
  'waiter',
  'enter-passenger-flow',
  'add-member',
  'member',
  'pen',
  'camera',
  'cumulative',
  'finish',
  'import',
  'vip',
  'dustbin',
  'accumulated-passenger-flow',
  'business-circle',
  'target',
  'user',
  'alarm-clock',
  'consumption',
  'account-number',
  'password',
  'email',
  'history',
  'data-analysis',
  'compare',
  'staff-management',
  'data-screening',
  'visit-Statistics',
  'area-hot',
  'play',
  'passenger-flow',
  'data-screen',
  'benefits',
  'shopping',
  'manager',
  'male',
  'age-distribution',
  'bind-account',
  'female',
  'double-arrow-up',
  'double-arrow-down',
  'arraw-vertical',
  'calendar',
  'search',
  'new-customer',
  'close',
  'success-circle',
  'error-circle',
]

import Icon0 from './Icon0'
import Icon1 from './Icon1'
import Icon2 from './Icon2'
import Icon3 from './Icon3'

export { Icon0, Icon1, Icon2, Icon3 }
