const CLASS_PREFIX = 'sui-'

// Color
const PRIMARY_COLOR = '#4883FB'
const INFO_COLOR = '#2db7f5'
const SUCCESS_COLOR = '#2AD1B0'
const WARNING_COLOR = '#F49857'
const ERROR_COLOR = '#F94545'
const NORMAL_COLOR = '#e6ebf1'
const CANCEL_COLOR = '#C9C9C9'

const WHITE = '#fff'
const BLACK = '#000'
const GRAY = '#999'

const DEFAULT_FONT_COLOR = '#4A4A4A'
const LIGHT_FONT_COLOR = '#7D7D7D'

// Font
const REGULAR_FONT_FAMILY = 'PingFangSC-Regular'
const MEDIUM_FONT_FAMILY = '.PingFangSC-Medium'

const LIGHTER_FONT_WEIGHT = 'lighter'
const NORMAL_FONT_WEIGHT = 'normal'
const BOLD_FONT_WEIGHT = 'bold'
const BOLDER_FONT_WEIGHT = 'bolder'

const SMALLER_SIZE = '12'
const SMALL_SIZE = '14'
const NORMAL_SIZE = '16'
const LARGE_SIZE = '18'
const LARGER_SIZE = '20'

const WITHOUT_ATTRS = ['class', 'staticClass', 'style', 'staticStyle']

export {
  CLASS_PREFIX,
  PRIMARY_COLOR,
  INFO_COLOR,
  SUCCESS_COLOR,
  WARNING_COLOR,
  ERROR_COLOR,
  NORMAL_COLOR,
  CANCEL_COLOR,
  WHITE,
  BLACK,
  GRAY,
  DEFAULT_FONT_COLOR,
  LIGHT_FONT_COLOR,
  REGULAR_FONT_FAMILY,
  MEDIUM_FONT_FAMILY,
  LIGHTER_FONT_WEIGHT,
  NORMAL_FONT_WEIGHT,
  BOLD_FONT_WEIGHT,
  BOLDER_FONT_WEIGHT,
  SMALLER_SIZE,
  SMALL_SIZE,
  NORMAL_SIZE,
  LARGE_SIZE,
  LARGER_SIZE,
  WITHOUT_ATTRS,
}
